name:                dandan
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/dandan#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
category:            Web

default-extensions:
- Strict
- StrictData

ghc-options:
- -threaded
- -O1

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-lens
  - vty
  - gogol
  - gogol-apps-calendar
  - lens
  - text
  - bytestring
  - ansi-wl-pprint
  - rainbow
  - optparse-applicative
  - directory
  - time
  - persistent
  - persistent-sqlite
  - persistent-template
  - containers
  - split
  - process
  - mtl
  - resourcet
  - monad-logger

executables:
  dandan:
    source-dirs:      src
    main:             Main.hs
