name:                dandan
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/dandan#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-lens
  - vty
  - gogol
  - gogol-apps-calendar
  - lens
  - text
  - bytestring

executables:
  dandan:
    source-dirs:      src
    main:             Main.hs
